version: 0.2

phases:
  install:
    commands:
      - echo "⚠️ Forzando instalación de Node.js 20..."
      - npm install -g n
      - n 20
      - hash -r
      - node -v
      - npm -v
      - echo "Instalando dependencias..."
      - npm ci
  pre_build:
    commands:
      - echo "Verificando entorno..."
      - node --version
  build:
    commands:
      - echo "Compilando aplicación..."
      - npm run build
      - echo "Verificando compilación..."
      - ls -la dist/
      - echo "Moviendo archivos compilados a la raíz (Requisito para EB)..."
      - cp -r dist/* .
  post_build:
    commands:
      - echo "Limpiando dependencias de desarrollo..."
      - rm -rf node_modules
      - npm ci --omit=dev
artifacts:
  files:
    - '**/*'
  discard-paths: no
