version: 0.2

phases:
  install:
    commands:
      - echo "Forcing install of Node.js 20..."
      - npm install -g n
      - n 20
      - hash -r
      - node -v
      - npm -v
      - echo "Installing project dependencies..."
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo "Verifying build output..."
      - ls -la dist/
      - echo "Moving dist files to root..."
      - cp -r dist/* .
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf node_modules
      - npm ci --omit=dev
artifacts:
  files:
    - '**/*'
  discard-paths: no
