version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - echo "Construyendo la aplicación..."
      - npm run build
      - echo "Verificando contenido de dist..."
      - ls -R dist/
  post_build:
    commands:
      - echo "Empaquetando para Elastic Beanstalk..."
      - mkdir deployment_package
      - cp -r dist deployment_package/
      - cp package.json deployment_package/
      - cp package-lock.json deployment_package/
      - cp Procfile deployment_package/
      - cp -r .platform deployment_package/
      - echo "Contenido del paquete de despliegue:"
      - ls -R deployment_package/

artifacts:
  files:
    - '**/*'
  base-directory: deployment_package