version: 0.2

phases:
  install:
    commands:
      - echo "Current Node version:"
      - node -v
      - echo "Downloading Node.js 20..."
      - curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      - yum install -y nodejs
      - echo "New Node version:"
      - node -v
      - npm -v
      - echo "Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - echo "Checking dist folder..."
      - ls -R dist/
      - echo "Moving dist files..."
      - cp -r dist/* .
  post_build:
    commands:
      - echo Build completed on `date`
      - rm -rf node_modules
      - npm ci --omit=dev
artifacts:
  files:
    - '**/*'
  discard-paths: no
