version: 0.2

# AWS CodeBuild buildspec para yo-participo-api
# Este archivo define cómo AWS CodeBuild debe construir y desplegar la aplicación

phases:
  # Fase de instalación: instalar dependencias
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependencias..."
      - npm ci

  # Fase de pre-build: verificar configuración
  pre_build:
    commands:
      - echo "Verificando versiones..."
      - node --version
      - npm --version
      - echo "Pre-build completado"

  # Fase de build: compilar la aplicación
  build:
    commands:
      - echo "Compilando aplicación NestJS..."
      - npm run build
      - echo "Build completado exitosamente"

  # Fase de post-build: preparar artefactos
  post_build:
    commands:
      - echo "Preparando artefactos para despliegue..."
      - echo "Verificando carpeta dist..."
      - ls -la dist/
      - echo "Limpiando devDependencies..."
      - npm prune --production
      - echo "Verificando que dist sigue existiendo..."
      - ls -la dist/
      - echo "Build finalizado en $(date)"

# Artefactos a guardar después del build
artifacts:
  files:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'package.json'
    - 'package-lock.json'
    - 'Procfile'
    - '.ebextensions/**/*'
    - '.npmrc'

# Caché para acelerar builds futuros
cache:
  paths:
    - 'node_modules/**/*'
